### ISSUE TITLE
Add manually labelled images

### ISSUE THREAD

**Issue by prabindh** [prabindh/ctsoc-ewaste#4]
Can we add the manually labelled images - link to dataset ?

**Comment by rdassi** [comment]
In the link for the whole dataset there are folders which have the manually labelled images (in folders bulb and battery)

**Comment by prabindh** [comment]
Ok. Linking dataset here (from readme) for posterity.
https://drive.google.com/drive/folders/1wd0a6sj9dQ59G9PwsS6bXiGG0ed9HSlJ?usp=sharing
