### ISSUE TITLE
Add images specific to India - for bulb, battery classes

### ISSUE THREAD

**Issue by prabindh** [prabindh/ctsoc-ewaste#5]
Add images specific to India - for bulb, battery classes. The images in this dataset, are not specific to India, and more found on other countries products.

**Comment by rdassi** [comment]
Added around 100 images specific to India and with multiple objects from different classes. Identified by `ind-number` in the dataset uploaded on  ![Google Drive](https://drive.google.com/drive/folders/1Zk47mWlZQYjBsesMEGJjCQNrwDGpB-Tl)

**Comment by prabindh** [comment]
github having issues showing the googledrive link - Is this the one ? 

https://drive.google.com/drive/folders/1Zk47mWlZQYjBsesMEGJjCQNrwDGpB-Tl

**Comment by rdassi** [comment]
Yes sir this is the link
