### ISSUE TITLE
Detailed steps on Augmentation

### ISSUE THREAD

**Issue by prabindh** [prabindh/ctsoc-ewaste#6]
Please add the detailed steps (including screenshots) of how the augmentation via Roboflow was achieved.

Instead of writing in the README `[ Processing done via Roboflow ]`, this will be more useful.

- Screenshots
- How many input images, how many output augmented images

**Comment by rdassi** [comment]
Added details in README.md for dataset ![here](https://github.com/prabindh/ctsoc-ewaste/tree/main/dataset)
